### ISSUE TITLE
System.MissingMethodException thrown from HidDevices.Enumerate

### ISSUE THREAD

**Issue by AngusMcIntyre** [mikeobrien/HidLibrary#47]
Hi Mike and friends,

I recently upgraded my Nuget package from **3.2.23** to **3.2.29** and am receiving a `MissingMethodException` when enumerating my device,
### Exception content

```
System.MissingMethodException was unhandled
  HResult=-2146233069
  Message=Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
  Source=HidLibrary
  StackTrace:
       at HidLibrary.HidDevices.EnumerateDevices()
       at HidLibrary.HidDevices.Enumerate(Int32 vendorId, Int32[] productIds) in d:\TeamCity\BuildAgent\work\26c2362cad24d4c8\src\HidLibrary\HidDevices.cs:line 35
       at HIDDeviceTest.Program.Main(String[] args) in x:\GitFlow\XP01\HIDDeviceTest\HIDDeviceTest\Program.cs:line 22
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:
```
### Environment
- The exception happens with all overloads and is not present in version **3.2.28**.
- I have .NET Framework 4.5 installed but no higher that I can see.
- Operating System: Windows 7 x64

I imagine the .NET version is the problem but I wanted to let you know. I'm fairly sure Nuget shouldn't have let me add it to me project!

**Comment by Yitzchok** [comment]
Installing the latest version of .NET help me with this problem.
